# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

INSERT INTO country(name,nationality) VALUES
('Afghanistan','Afghan'),
('Albania',''),
('Algeria','Algerian'),
('American Samoa',''),
('Andorra',''),
('Angola',''),
('Anguilla',''),
('Antartica',''),
('Antigua & Barbuda',''),
('Argentina',''),
('Armenia',''),
('Aruba',''),
('Australia',''),
('Azerbaijan',''),
('Albania',''),
('Bahamas, The',''),
('Bahrain',''),
('Bangladesh',''),
('Barbados',''),
('Belarus',''),
('Belgium',''),
('Belize',''),
('Benin',''),
('Bermuda',''),
('Bhutan',''),
('Bolivia',''),
('Bonaire, St.Eustat, Saba',''),
('Bosnia and Herzegovina',''),
('Botswana',''),
('Bouvet Island',''),
('Brazil',''),
('British Indian Ocean Territories',''),
('British Virgin Islands',''),
('Brunel Darussalam',''),
('Bulgaria',''),
('Burkina Faso',''),
('Burundi',''),
('Cambodia',''),
('Cameroon',''),
('Canada',''),
('Cape Verde',''),
('Cayman Islands',''),
('Central African Republic',''),
('Chad',''),
('Chile',''),
('China',''),
('Christmas Ismand',''),
('Cocos (Keeling) Islands',''),
('Colombia',''),
('Comoros',''),
('Congo',''),
('Congo, Dem. Rep. of the',''),
('Cook Islands',''),
('Costa Rica',''),
('Cote D''Ivoire',''),
('Croatia',''),
('Cyprus',''),
('Czech Republic',''),
('Denmark',''),
('Djibouti',''),
('Dominica',''),
('Dominican Republic',''),
('East Timor (Timor-Leste)',''),
('Ecuador',''),
('Egypt',''),
('El Salvador',''),
('Equatorial Guinea',''),
('Eritrea',''),
('Estonia',''),
('Ethiopia',''),
('Falkland Islands (Malvinas)',''),
('Faroe Islands',''),
('Fiji',''),
('Finland',''),
('France','French'),
('French Guiana',''),
('French Polynesia',''),
('French Southern Terr.',''),
('Gabon',''),
('Gambia, the',''),
('Georgia',''),
('Germany',''),
('Ghana',''),
('Gibraltar',''),
('Greece',''),
('Greenland',''),
('Grenada',''),
('Guadeloupe',''),
('Guam',''),
('Guatemala',''),
('Guernesey and Aldernesey',''),
('Guiana, French',''),
('Guiana',''),
('Guiana-Bissau',''),
('Guiana, Equatorial',''),
('Guyana',''),
('Heard & McDonald Is.(AU)',''),
('Honduras',''),
('Hong Kong, (China)',''),
('Hungary',''),
('Iceland',''),
('India',''),
('Indonesia',''),
('Iran, Islamic Republic of',''),
('Iraq',''),
('Ireland',''),
('Israel',''),
('Italy',''),
('Jamaica',''),
('Japan',''),
('Jersey',''),
('Jordan',''),
('Kazakhstan',''),
('Kenya',''),
('Kiribati',''),
('Korea Dem. People''s Rep.',''),
('Korea, (South) Republic of',''),
('Kosovo',''),
('Kuwait',''),
('Kyrgyzstan',''),
('Lao People''s Democ. Rep.',''),
('Latvia',''),
('Lebanon',''),
('Lesotho',''),
('Liberia',''),
('Libyan Arab Jamahiriya',''),
('Liechtenstein',''),
('Lithuania',''),
('Luxemburg',''),
('Macao, (China)',''),
('Macedonia, TFYR',''),
('Madagascar',''),
('Malawi',''),
('Malaysia',''),
('Maldives',''),
('Mali',''),
('Malta',''),
('Maldives',''),
('Man, Isle of',''),
('Marshall Islands',''),
('Martinique (FR)',''),
('Mauritania',''),
('Mauritius',''),
('Mayotte (FR)',''),
('Mexico',''),
('Micronesia, Fed. States of',''),
('Moldove, Republic of',''),
('Monaco',''),
('Mongolia',''),
('Montenegro',''),
('Montserrat',''),
('Morocco',''),
('Mozambique',''),
('Myanmar (ex-Burma)',''),
('Namibia',''),
('Nauru',''),
('Nepal',''),
('Netherlands',''),
('Nethelands Antilles',''),
('New Caledonia',''),
('New Zealand',''),
('Nicaragua',''),
('Niger',''),
('Nigeria',''),
('Norfolk Island',''),
('Northern Mariana Islands',''),
('Norway',''),
('Oman',''),
('Pakistan',''),
('Palau',''),
('Palestinian Territory',''),
('Panama',''),
('Papua New Guinea',''),
('Paraguay',''),
('Peru',''),
('Philippines',''),
('Pitcairn Island',''),
('Poland',''),
('Portugal',''),
('Puerto Rico',''),
('Qatar',''),
('Reunion (FR)',''),
('Romania',''),
('Russia (Russian Fed.)',''),
('Rwanda',''),
('Sahara, Western',''),
('Saint Barthelemy (FR)',''),
('Saint Helena (UK)',''),
('Saint Kitts and Nevis',''),
('Saint Lucia',''),
('Saint Martin (FR)',''),
('Saint Pierre & Miquelon (FR)',''),
('Saint Vincent & Grenadines',''),
('Samoa',''),
('San Marino',''),
('Sao Tome and Principe',''),
('Saudi Arabia',''),
('Senegal',''),
('Serbia',''),
('Seychelles',''),
('Sierra Leone',''),
('Singapore',''),
('Slovakia',''),
('Slovenia',''),
('Solomon Islands',''),
('Somalia',''),
('South Africa',''),
('Saint George & Saint Sandwich',''),
('South Sudan',''),
('Spain',''),
('Sri Lanka',''),
('Sudan',''),
('Suriname',''),
('Svalbard & Jan Mayen Islands',''),
('Swaziland',''),
('Sweden',''),
('Switzerland',''),
('Syrian Arab Republic',''),
('Taiwan',''),
('Tajikistan',''),
('Tanzania, United Rep. of',''),
('Thailand',''),
('Togo',''),
('Tokelau',''),
('Tonga',''),
('Trinidad & Tobago',''),
('Tunisia',''),
('Turkmenistan',''),
('Turks and Caicos Islands',''),
('Tuvalu',''),
('Uganda',''),
('Ukraine',''),
('United Arab Emirates',''),
('United Kingdom',''),
('United States',''),
('US Minor Outlying Islands',''),
('Uruguay',''),
('Uzbekistan',''),
('Vanuatu',''),
('Vatican (Holy See)',''),
('Venezuela',''),
('Viet Nam',''),
('Virgin Islands, British',''),
('Virgin Islands, U.S.',''),
('Wallis and Futuna',''),
('Yemen',''),
('Zambia',''),
('Zimbabwe','');

# --- !Downs

SET FOREIGN_KEY_CHECKS=0;

DELETE FROM country;

SET FOREIGN_KEY_CHECKS=1;
